name: Vulnerability Scan

on:
  schedule:
  - cron: '0 * * * *'

jobs:
  nuget-vulnerability-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - run: dotnet restore ./dotnet/Solution1.sln
      - run: |
          dotnet list ./dotnet/Solution1.sln package --vulnerable --include-transitive
          if [ $? -ne 0 ]; then exit 1; fi